name: Test and Build and Push Docker Image

on:
  push:
    branches: ['main']
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: europe-west4-docker.pkg.dev/impl-383520/docker
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  run-cypress-test:
    runs-on: ubuntu-22.04

    concurrency:
      group: cypress_test
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          quiet: false
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker-image:

    needs: run-cypress-test

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    concurrency:
      group: docker_build
      cancel-in-progress: true

    permissions:
      contents: read

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Configure docker'
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          tags: type=raw,value=latest,enable={{is_default_branch}}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
