on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          skip-github-pull-request: false

      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ steps.release.outputs.releases_created }}
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        if: ${{ steps.release.outputs.releases_created }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.releases_created }}
        uses: docker/setup-buildx-action@v3

      - id: 'auth'
        if: ${{ steps.release.outputs.releases_created }}
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up gcloud Cloud SDK environment
        if: ${{ steps.release.outputs.releases_created }}
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: impl-383520

      - name: 'Configure docker'
        if: ${{ steps.release.outputs.releases_created }}
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet

      - name: Build and push docker image
        if: ${{ steps.release.outputs.releases_created }}
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SHORT_SHA=${{ github.sha }}

